<?php
//
// Copyright (c) ZeroC, Inc. All rights reserved.
//
//
// Ice version 3.7.5
//
// <auto-generated>
//
// Generated from file `Endpoint.ice'
//
// Warning: do not edit this file.
//
// </auto-generated>
//


namespace
{
    require_once 'Ice/Version.php';
    require_once 'Ice/BuiltinSequences.php';
    require_once 'Ice/EndpointF.php';
}

namespace Ice
{
    if(!defined('\\Ice\\TCPEndpointType'))
    {
        define(__NAMESPACE__ . '\\TCPEndpointType', 1);
    }
}

namespace Ice
{
    if(!defined('\\Ice\\SSLEndpointType'))
    {
        define(__NAMESPACE__ . '\\SSLEndpointType', 2);
    }
}

namespace Ice
{
    if(!defined('\\Ice\\UDPEndpointType'))
    {
        define(__NAMESPACE__ . '\\UDPEndpointType', 3);
    }
}

namespace Ice
{
    if(!defined('\\Ice\\WSEndpointType'))
    {
        define(__NAMESPACE__ . '\\WSEndpointType', 4);
    }
}

namespace Ice
{
    if(!defined('\\Ice\\WSSEndpointType'))
    {
        define(__NAMESPACE__ . '\\WSSEndpointType', 5);
    }
}

namespace Ice
{
    if(!defined('\\Ice\\BTEndpointType'))
    {
        define(__NAMESPACE__ . '\\BTEndpointType', 6);
    }
}

namespace Ice
{
    if(!defined('\\Ice\\BTSEndpointType'))
    {
        define(__NAMESPACE__ . '\\BTSEndpointType', 7);
    }
}

namespace Ice
{
    if(!defined('\\Ice\\iAPEndpointType'))
    {
        define(__NAMESPACE__ . '\\iAPEndpointType', 8);
    }
}

namespace Ice
{
    if(!defined('\\Ice\\iAPSEndpointType'))
    {
        define(__NAMESPACE__ . '\\iAPSEndpointType', 9);
    }
}
?>
