<?php
//
// Copyright (c) ZeroC, Inc. All rights reserved.
//
//
// Ice version 3.7.5
//
// <auto-generated>
//
// Generated from file `Identity.ice'
//
// Warning: do not edit this file.
//
// </auto-generated>
//


namespace Ice
{
    global $Ice__t_Identity;
    class Identity
    {
        public function __construct($name='', $category='')
        {
            $this->name = $name;
            $this->category = $category;
        }

        public function __toString()
        {
            global $Ice__t_Identity;
            return IcePHP_stringify($this, $Ice__t_Identity);
        }

        public $name;
        public $category;
    }

    global $IcePHP__t_string;
    $Ice__t_Identity = IcePHP_defineStruct('::Ice::Identity', '\\Ice\\Identity', array(
        array('name', $IcePHP__t_string),
        array('category', $IcePHP__t_string)));
}

namespace Ice
{
    global $Ice__t_IdentitySeq;

    if(!isset($Ice__t_IdentitySeq))
    {
        global $Ice__t_Identity;
        $Ice__t_IdentitySeq = IcePHP_defineSequence('::Ice::IdentitySeq', $Ice__t_Identity);
    }
}
?>
