<?php
//
// Copyright (c) ZeroC, Inc. All rights reserved.
//
//
// Ice version 3.7.5
//
// <auto-generated>
//
// Generated from file `SliceChecksumDict.ice'
//
// Warning: do not edit this file.
//
// </auto-generated>
//


namespace Ice
{
    global $Ice__t_SliceChecksumDict;

    if(!isset($Ice__t_SliceChecksumDict))
    {
        global $IcePHP__t_string;
        global $IcePHP__t_string;
        $Ice__t_SliceChecksumDict = IcePHP_defineDictionary('::Ice::SliceChecksumDict', $IcePHP__t_string, $IcePHP__t_string);
    }
}
?>
