<?php
// **********************************************************************
//
// Copyright (c) 2003-2016 ZeroC, Inc. All rights reserved.
//
// This copy of Ice is licensed to you under the terms described in the
// ICE_LICENSE file included in this distribution.
//
// **********************************************************************
//
// Ice version 3.6.3
//
// <auto-generated>
//
// Generated from file `Version.ice'
//
// Warning: do not edit this file.
//
// </auto-generated>
//


namespace Ice
{
    global $Ice__t_ProtocolVersion;

    if(!class_exists('\\Ice\\ProtocolVersion'))
    {
        class ProtocolVersion
        {
            public function __construct($major=0, $minor=0)
            {
                $this->major = $major;
                $this->minor = $minor;
            }

            public function __toString()
            {
                global $Ice__t_ProtocolVersion;
                return IcePHP_stringify($this, $Ice__t_ProtocolVersion);
            }

            public $major;
            public $minor;
        }

        $Ice__t_ProtocolVersion = IcePHP_defineStruct('::Ice::ProtocolVersion', '\\Ice\\ProtocolVersion', array(
            array('major', $IcePHP__t_byte), 
            array('minor', $IcePHP__t_byte)));
    }
}

namespace Ice
{
    global $Ice__t_EncodingVersion;

    if(!class_exists('\\Ice\\EncodingVersion'))
    {
        class EncodingVersion
        {
            public function __construct($major=0, $minor=0)
            {
                $this->major = $major;
                $this->minor = $minor;
            }

            public function __toString()
            {
                global $Ice__t_EncodingVersion;
                return IcePHP_stringify($this, $Ice__t_EncodingVersion);
            }

            public $major;
            public $minor;
        }

        $Ice__t_EncodingVersion = IcePHP_defineStruct('::Ice::EncodingVersion', '\\Ice\\EncodingVersion', array(
            array('major', $IcePHP__t_byte), 
            array('minor', $IcePHP__t_byte)));
    }
}
?>
